# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c502198fb7adf5a86ff2ad3d87c59967"
name = "inventorySync"
handle = "firgelli-inventory-sync"
application_url = "https://firgelli-inventory-sync.firgelli-inventory-sync.workers.dev/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_locations,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"
